### ISSUE TITLE
Refreshing while stepping bugs

### ISSUE THREAD

**Issue by gregtatum** [firefox-devtools/debugger#7193]
I was finding the debugger to be unreliable when I was breaking on something, refreshing, and stepping. I tried to find some errors, but they seem to be race conditions, which are hard to be exact on how to reproduce. So instead I entered into a bit more of a chaos mode with this STR:

* Use Nightly
* Load perf.html from the command line (probably any large sourcemapped project)
* Open up the debugger
* Open Root.js
* Put a breakpoint in render()
* Very quickly hit and alternate between `ctrl + '` and `ctrl + r`.

Error (not sure all of it is relevant, but I included it all for completeness)

```
onEvaluationResult threw an exception: No response handler for an evaluateJSAsync result (resultID: 1540850188931) ThreadSafeDevToolsUtils.js:88:5
onEvaluationResult threw an exception: No response handler for an evaluateJSAsync result (resultID: 1540850188947) ThreadSafeDevToolsUtils.js:88:5
onEvaluationResult threw an exception: No response handler for an evaluateJSAsync result (resultID: 1540850188954) ThreadSafeDevToolsUtils.js:88:5
onEvaluationResult threw an exception: No response handler for an evaluateJSAsync result (resultID: 1540850188962) ThreadSafeDevToolsUtils.js:88:5
onEvaluationResult threw an exception: No response handler for an evaluateJSAsync result (resultID: 1540850188967) ThreadSafeDevToolsUtils.js:88:5
onEvaluationResult threw an exception: No response handler for an evaluateJSAsync result (resultID: 1540850188976) ThreadSafeDevToolsUtils.js:88:5
Firefox can’t establish a connection to the server at ws://localhost:4242/sockjs-node/297/0ug2jx5i/websocket. b2213b0dcb412e02ef59.bundle.js:50335:9
The connection to ws://localhost:4242/sockjs-node/297/0ug2jx5i/websocket was interrupted while the page was loading. b2213b0dcb412e02ef59.bundle.js:50335:9
TypeError: NetworkError when attempting to fetch resource.
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 181"  data: no]
TypeError: frame is undefined; can't access its "location" property[Learn More] commands.js:246:48
uncaught exception: Error: Parser: source server1.conn8.child1/source28/originalSource-d3a677c275c242bb73db8613876b473c was not provided.
uncaught exception: Error: Parser: source server1.conn8.child1/source28/originalSource-e8611e9da3770a1c62e9ec1c4a085b06 was not provided.
TypeError: frame is undefined; can't access its "location" property[Learn More] commands.js:246:48
TypeError: frame is undefined; can't access its "location" property[Learn More]
commands.js:246:48
can't access dead object MessageChannel.jsm:989
Firefox can’t establish a connection to the server at ws://localhost:4242/sockjs-node/988/vdy3gnin/websocket. b2213b0dcb412e02ef59.bundle.js:50335:9
The connection to ws://localhost:4242/sockjs-node/988/vdy3gnin/websocket was interrupted while the page was loading. b2213b0dcb412e02ef59.bundle.js:50335:9

TypeError: "item is undefined; can't access its "contents" property"
	nodeHasChildren resource://devtools/client/shared/components/reps/reps.js:2952:3
	nodeIsPrimitive resource://devtools/client/shared/components/reps/reps.js:3014:11
	shouldRenderRootsInReps resource://devtools/client/shared/components/reps/reps.js:1630:61
	exports resource://devtools/client/shared/components/reps/reps.js:6545:7
	mountIndeterminateComponent resource://devtools/client/shared/vendor/react-dom.js:10501:13
	beginWork resource://devtools/client/shared/vendor/react-dom.js:10890:14
	performUnitOfWork resource://devtools/client/shared/vendor/react-dom.js:12713:12
	workLoop resource://devtools/client/shared/vendor/react-dom.js:12730:24
	renderRoot resource://devtools/client/shared/vendor/react-dom.js:12770:7
	performWorkOnRoot resource://devtools/client/shared/vendor/react-dom.js:13359:22
	performWork resource://devtools/client/shared/vendor/react-dom.js:13281:7
	performSyncWork resource://devtools/client/shared/vendor/react-dom.js:13253:3
	requestWork resource://devtools/client/shared/vendor/react-dom.js:13153:5
	1 resource://devtools/client/shared/vendor/react-dom.js:13022:11
	enqueueSetState resource://devtools/client/shared/vendor/react-dom.js:8845:5
	setState resource://devtools/client/shared/vendor/react.js:406:3
	onStateChange resource://devtools/client/shared/vendor/react-redux.js:1412:11
	notify resource://devtools/client/shared/vendor/react-redux.js:1159:21
	notifyNestedSubs resource://devtools/client/shared/vendor/react-redux.js:1198:5
	onStateChange resource://devtools/client/shared/vendor/react-redux.js:1409:11
	notify resource://devtools/client/shared/vendor/react-redux.js:1159:21
	notifyNestedSubs resource://devtools/client/shared/vendor/react-redux.js:1198:5
	onStateChange resource://devtools/client/shared/vendor/react-redux.js:1409:11
	dispatch resource://devtools/client/shared/vendor/redux.js:416:7
	waitUntilService resource://devtools/client/debugger/new/src/actions/utils/middleware/wait-service.js:71:20
	promiseMiddleware resource://devtools/client/debugger/new/src/actions/utils/middleware/promise.js:31:14
	thunk resource://devtools/client/debugger/new/src/actions/utils/middleware/thunk.js:31:100
	dispatch resource://devtools/client/shared/vendor/redux.js:755:18
	promiseMiddleware resource://devtools/client/debugger/new/src/actions/utils/middleware/promise.js:49:11
  
react-dom.js:11273:5
TypeError: item is undefined; can't access its "contents" property[Learn More] reps.js:2952:3
error occurred while processing 'evaluateJSAsync: TypeError: getFrameDbg(...) is undefined
Stack: exports.evalWithDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:1048:22
evaluateJSAsync@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:957:22
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1313:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/child-transport.js:66:5
enter@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/event-loop.js:118:5
_pushThreadPause@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond@resource://devtools/shared/base-loader.js -> resource://devtools/server/a
main.js:1168

TypeError: store is null; can't access its "dispatch" property[Learn More] webconsole-output-wrapper.js:451:9
```

Also, things got really slow doing this, although perhaps it's something to do with reporting errors with the browser console open:

http://bit.ly/2Q8L81n

Here is another error:

```
evalWithDebugger threw an exception: Error: The frame actor was not found: server1.conn10.child1/frame867
Stack: getFrameDbg@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:256:5
exports.evalWithDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:1048:22
evaluateJSAsync@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:957:22
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1313:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/child-transport.js:66:5
enter@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/event-loop.js:118:5
_pushThreadPause@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:493:7
hit@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/breakpoint.js:189:12
render@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:61212:1
finishClassComponent@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33512:22
updateClassComponent@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33489:12
beginWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33864:16
performUnitOfWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35863:16
workLoop@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35927:26
callCallback@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26181:9
invokeGuardedCallbackDev@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26220:7
invokeGuardedCallback@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26077:5
renderRoot@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36005:7
performWorkOnRoot@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36653:24
performWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36606:7
requestWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36517:7
scheduleWorkImpl@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36371:11
scheduleWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36328:12
scheduleTopLevelUpdate@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36832:5
updateContainer@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36870:7
renderSubtreeIntoContainer/<@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40865:7
unbatchedUpdates@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36741:12
renderSubtreeIntoContainer@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40864:5
render@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40929:12
./src/index.js@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:74481:1
__webpack_require__@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
0@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:87909:18
__webpack_require__@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:249:18
@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:1:11
Line: 256, column: 5 ThreadSafeDevToolsUtils.js:88:5
reportException
resource://devtools/shared/ThreadSafeDevToolsUtils.js:88:5
getFrameDbg
resource://devtools/server/actors/webconsole/eval-with-debugger.js:255:10
exports.evalWithDebugger
resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS
resource://devtools/server/actors/webconsole.js:1048:22
evaluateJSAsync
resource://devtools/server/actors/webconsole.js:957:22
onPacket
resource://devtools/server/main.js:1313:15
receiveMessage
resource://devtools/shared/transport/child-transport.js:66:5
enter
resource://devtools/server/actors/utils/event-loop.js:118:5
_pushThreadPause
resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond
resource://devtools/server/actors/thread.js:493:7
hit
resource://devtools/server/actors/breakpoint.js:189:12
render
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:61212:1
finishClassComponent
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33512:22
updateClassComponent
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33489:12
beginWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33864:16
performUnitOfWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35863:16
workLoop
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35927:26
callCallback
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26181:9
invokeGuardedCallbackDev
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26220:7
invokeGuardedCallback
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26077:5
renderRoot
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36005:7
performWorkOnRoot
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36653:24
performWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36606:7
requestWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36517:7
scheduleWorkImpl
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36371:11
scheduleWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36328:12
scheduleTopLevelUpdate
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36832:5
updateContainer
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36870:7
renderSubtreeIntoContainer/<
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40865:7
unbatchedUpdates
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36741:12
renderSubtreeIntoContainer
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40864:5
render
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40929:12
./src/index.js
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:74481:1
__webpack_require__
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
0
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:87909:18
__webpack_require__
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
<anonymous>
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:249:18
<anonymous>
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:1:11
```

```
error occurred while processing 'evaluateJSAsync: TypeError: getFrameDbg(...) is undefined
Stack: exports.evalWithDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:1048:22
evaluateJSAsync@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:957:22
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1313:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/child-transport.js:66:5
enter@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/event-loop.js:118:5
_pushThreadPause@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond@resource://devtools/shared/base-loader.js -> resource://devtools/server/a main.js:1168
_unknownError
resource://devtools/server/main.js:1168:5
onPacket
resource://devtools/server/main.js:1316:29
receiveMessage
resource://devtools/shared/transport/child-transport.js:66:5
enter
resource://devtools/server/actors/utils/event-loop.js:118:5
enter self-hosted:972:17 _pushThreadPause
resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond
resource://devtools/server/actors/thread.js:493:7
hit
resource://devtools/server/actors/breakpoint.js:189:12
render
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:61212:1
finishClassComponent
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33512:22
updateClassComponent
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33489:12
beginWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33864:16
performUnitOfWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35863:16
workLoop
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35927:26
callCallback
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26181:9
invokeGuardedCallbackDev
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26220:7
invokeGuardedCallback
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26077:5
renderRoot
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36005:7
performWorkOnRoot
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36653:24
performWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36606:7
requestWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36517:7
scheduleWorkImpl
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36371:11
scheduleWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36328:12
scheduleTopLevelUpdate
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36832:5
updateContainer
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36870:7
renderSubtreeIntoContainer/<
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40865:7
unbatchedUpdates
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36741:12
renderSubtreeIntoContainer
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40864:5
render
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40929:12
./src/index.js
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:74481:1
__webpack_require__
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
0
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:87909:18
__webpack_require__
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
<anonymous>
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:249:18
<anonymous>
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:1:11
```

```
error occurred while processing 'evaluateJSAsync: TypeError: getFrameDbg(...) is undefined
Stack: exports.evalWithDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:1048:22
evaluateJSAsync@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:957:22
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1313:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/child-transport.js:66:5
enter@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/event-loop.js:118:5
_pushThreadPause@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond@resource://devtools/shared/base-loader.js -> resource://devtools/server/a main.js:1168
_unknownError
resource://devtools/server/main.js:1168:5
onPacket
resource://devtools/server/main.js:1316:29
receiveMessage
resource://devtools/shared/transport/child-transport.js:66:5
enter
resource://devtools/server/actors/utils/event-loop.js:118:5
enter self-hosted:972:17 _pushThreadPause
resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond
resource://devtools/server/actors/thread.js:493:7
hit
resource://devtools/server/actors/breakpoint.js:189:12
render
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:61212:1
finishClassComponent
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33512:22
updateClassComponent
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33489:12
beginWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33864:16
performUnitOfWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35863:16
workLoop
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35927:26
callCallback
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26181:9
invokeGuardedCallbackDev
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26220:7
invokeGuardedCallback
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26077:5
renderRoot
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36005:7
performWorkOnRoot
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36653:24
performWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36606:7
requestWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36517:7
scheduleWorkImpl
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36371:11
scheduleWork
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36328:12
scheduleTopLevelUpdate
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36832:5
updateContainer
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36870:7
renderSubtreeIntoContainer/<
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40865:7
unbatchedUpdates
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36741:12
renderSubtreeIntoContainer
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40864:5
render
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40929:12
./src/index.js
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:74481:1
__webpack_require__
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
0
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:87909:18
__webpack_require__
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
<anonymous>
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:249:18
<anonymous>
http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:1:11
```

Another one:

```
evalWithDebugger threw an exception: Error: The frame actor was not found: server1.conn10.child1/frame867
Stack: getFrameDbg@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:256:5
exports.evalWithDebugger@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:1048:22
evaluateJSAsync@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:957:22
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1313:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/child-transport.js:66:5
enter@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/event-loop.js:118:5
_pushThreadPause@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:185:5
_pauseAndRespond@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:493:7
hit@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/breakpoint.js:189:12
render@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:61212:1
finishClassComponent@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33512:22
updateClassComponent@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33489:12
beginWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:33864:16
performUnitOfWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35863:16
workLoop@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:35927:26
callCallback@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26181:9
invokeGuardedCallbackDev@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26220:7
invokeGuardedCallback@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:26077:5
renderRoot@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36005:7
performWorkOnRoot@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36653:24
performWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36606:7
requestWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36517:7
scheduleWorkImpl@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36371:11
scheduleWork@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36328:12
scheduleTopLevelUpdate@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36832:5
updateContainer@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36870:7
renderSubtreeIntoContainer/<@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40865:7
unbatchedUpdates@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:36741:12
renderSubtreeIntoContainer@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40864:5
render@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:40929:12
./src/index.js@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:74481:1
__webpack_require__@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
0@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:87909:18
__webpack_require__@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:81:12
@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:249:18
@http://localhost:4242/b2213b0dcb412e02ef59.bundle.js:1:11
Line: 256, column: 5
```

**Comment by jasonLaster** [comment]
@gregtatum mind re-testing this?

**Comment by darkwing** [comment]
@gregtatum Have you seen this recently?

**Comment by tiansh** [comment]
```
error occurred while processing 'evaluateJSAsync: TypeError: getFrameDbg(...) is undefined
Stack: exports.evalWithDebugger@resource://devtools/server/actors/webconsole/eval-with-debugger.js:84:26
evaluateJS@resource://devtools/server/actors/webconsole.js:1005:22
evaluateJSAsync@resource://devtools/server/actors/webconsole.js:910:27
onPacket@resource://devtools/server/main.js:1291:58
receiveMessage@resource://devtools/shared/transport/child-transport.js:66:16
enter@resource://devtools/server/actors/utils/event-loop.js:118:18
_pushThreadPause@resource://devtools/server/actors/thread.js:187:15
_pauseAndRespond@resource://devtools/server/actors/thread.js:549:12
hit@resource://devtools/server/actors/breakpoint.js:253:29
@moz-extension://0a6ab92f-19c0-45d9-8c43-bcb29f35b982/background/controller/request/blocking.js:49:9
Line: 84, column: 26 10 main.js:1160
    _unknownError resource://devtools/server/main.js:1160
    onPacket resource://devtools/server/main.js:1294
    receiveMessage resource://devtools/shared/transport/child-transport.js:66
    enter resource://devtools/server/actors/utils/event-loop.js:118
    enter self-hosted:1001
    _pushThreadPause resource://devtools/server/actors/thread.js:187
    _pauseAndRespond resource://devtools/server/actors/thread.js:549
    hit resource://devtools/server/actors/breakpoint.js:253
    <anonymous> moz-extension://0a6ab92f-19c0-45d9-8c43-bcb29f35b982/background/controller/request/blocking.js:49
    AsyncFunctionNext self-hosted:839
```

Just got this with slightly different line numbers on Firefox 68.0.1

**Comment by tiansh** [comment]
I'm not sure if it related, but seems to be.

```html
<script>
  async function doStuff(value) {
    console.log(value);
    await new Promise(resolve => setTimeout(resolve, value));
    console.log(value);
  }
  doStuff(200);
  doStuff(100);
</script>
```

* Debugging on Nightly 70.0a1 (2019-08-15) (64-bit).
* Add break points on two `console.log` line
* Refresh the page
* Hit F8 twice
* And...
<img width="760" alt="fx-debugger" src="https://user-images.githubusercontent.com/6500326/63145419-be02c700-c03a-11e9-801f-dc2e4fa68797.png">

**Comment by janodvarko** [comment]
@bhackett1024 can you reproduce this?
Or is this already fixed?

Honza

**Comment by janodvarko** [comment]
It's been a while since this was reported, should be / could be fixed.

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
