### ISSUE TITLE
Sourcemapping url with a data uri - FF does not use the sourcemap.

### ISSUE THREAD

**Issue by raghur** [firefox-devtools/debugger#7613]
I'm developing an app in vue.js with Karma and webpack. While debugging in browser, the sourcemap is specified with a //# sourcemappingurl = and a data uri with the source map. This seems to work fine in Chrome but not in FF (57). I prefer to use FF but in this case am forced to use Chrome. I checked bugzilla and googled a bit but it's unclear if there's a reason why firefox doesn't support this.

**Comment by jasonLaster** [comment]
@raghur i just tried to reproduce and could not run `npm run test:debug`

```
➜  vuejs2-typescript-starter node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js
Hash: c1d4e8afb52d40031a6c
Version: webpack 3.12.0
Child
    Hash: c1d4e8afb52d40031a6c
    Time: 1759ms
                                   Asset      Size  Chunks                    Chunk Names
    89889688147bd7575d6327160d64e760.svg    109 kB          [emitted]
                               vendor.js    674 kB       0  [emitted]  [big]  vendor
                              vendor.css    315 kB       0  [emitted]  [big]  vendor
                           vendor.js.map    852 kB       0  [emitted]         vendor
                          vendor.css.map  87 bytes       0  [emitted]         vendor
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/bootstrap/dist/css/bootstrap.css:
         1 asset
➜  vuejs2-typescript-starter npm run test:debug

> netcore@0.0.0 test:debug /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter
> node node_modules/karma/bin/karma start --no-single-run --debug --browsers PhantomJS

Is Debugging true
Is running tests: 1
Dev Build: true
Starting type checking service...
Using 1 worker with 2048MB memory limit
resolve failed:  { Error: Cannot find module 'pn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.requireRelative.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:108:13
    at Array.map (<anonymous>)
    at loadPreset (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:100:29)
    at module.exports (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/index.js:88:19)
    at Object.<anonymous> (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/babel-preset-es2015-mod/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' } pn
node_modules/nan
mootools already loaded
resolve failed:  { Error: Cannot find module '@types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.requireRelative.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:108:13
    at Array.map (<anonymous>)
    at loadPreset (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:100:29)
    at module.exports (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/index.js:88:19)
    at Object.<anonymous> (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/babel-preset-es2015-mod/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' } @types
resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.requireRelative.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:108:13
    at Array.map (<anonymous>)
    at loadPreset (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:100:29)
    at module.exports (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/index.js:88:19)
    at Object.<anonymous> (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/babel-preset-es2015-mod/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.requireRelative.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:108:13
    at Array.map (<anonymous>)
    at loadPreset (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:100:29)
    at module.exports (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/index.js:88:19)
    at Object.<anonymous> (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/babel-preset-es2015-mod/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { Error: Cannot find module '@vue'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.requireRelative.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:108:13
    at Array.map (<anonymous>)
    at loadPreset (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:100:29)
    at module.exports (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/index.js:88:19)
    at Object.<anonymous> (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/babel-preset-es2015-mod/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' } @vue
resolve failed:  { Error: Cannot find module '@sinonjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.requireRelative.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:108:13
    at Array.map (<anonymous>)
    at loadPreset (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/lib/serialize.js:100:29)
    at module.exports (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/modify-babel-preset/index.js:88:19)
    at Object.<anonymous> (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/babel-preset-es2015-mod/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' } @sinonjs
(node:19039) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
(node:19039) [DEP0027] DeprecationWarning: util.puts is deprecated. Use console.log instead.
(node:19039) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
04 01 2019 12:11:22.132:ERROR [karma]: TypeError: Cannot read property 'length' of undefined
    at NormalModuleFactory.resolveRequestArray (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/webpack/lib/NormalModuleFactory.js:249:12)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/moo-server/mootools.js:710:16
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:3880:24
    at eachOfArrayLike (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:1069:9)
    at eachOf (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:1117:5)
    at _parallel (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit [as parallel] (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:3962:5)
    at asyncLib.parallel (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/webpack/lib/NormalModuleFactory.js:188:14)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:3888:9
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:1064:13)
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:969:16
    at /Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/webpack/lib/NormalModuleFactory.js:120:7)
    at onResolve (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at innerCallback (/Users/jlaster/src/_daily/Jan-04/vuejs2-typescript-starter/node_modules/enhanced-resolve/lib/Resolver.js:143:22)
(node:19039) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netcore@0.0.0 test:debug: `node node_modules/karma/bin/karma start --no-single-run --debug --browsers PhantomJS`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netcore@0.0.0 test:debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by loganfsmyth** [comment]
We've fixed a bunch of sourcemap issues in the last few months, so I'm going to close this as likely fixed. It anyone wants to test, make sure to look at Nightly or Beta. If there are still any issues, please file on Bugzilla.
