### ISSUE TITLE
Copy scripts are out of date

### ISSUE THREAD

**Issue by sorin-davidoi** [firefox-devtools/debugger#8204]
```bash
$ ./bin/prepare-mochitests-dev
$ yarn copy

(node:21761) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/user/Repositories/debugger/firefox/devtools/client/debugger/new/README.mozilla'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at writeReadme (/home/sorin/Repositories/debugger/bin/writeReadme.js:48:25)
    at start (/home/sorin/Repositories/debugger/bin/copy-assets.js:276:3)
    at module.exports (/home/sorin/Repositories/debugger/bin/copy-assets.js:359:12)
    at copy (/home/sorin/Repositories/debugger/bin/copy.js:41:13)
    at start (/home/sorin/Repositories/debugger/bin/copy.js:60:10)
    at Object.<anonymous> (/home/sorin/Repositories/debugger/bin/copy.js:117:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
(node:21761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by varundey** [comment]
Is this still up for grabs? @dczombera are you still working on it?

**Comment by dczombera** [comment]
@varundey This problem was already fixed by @darkwing a month ago or something. Might be a good idead to close this one.

**Comment by Anzumana** [comment]
@jasonLaster could you close this one? Getting rdy for hacktoberfest. Hopefully with some good prs :).

**Comment by jasonLaster** [comment]
@Anzumana we're working in firefox's repo these days

http://firefox-dev.tools

**Comment by Anzumana** [comment]
@jasonLaster i am a bit confused is this repo dead ? or how does it work

**Comment by nchevobbe** [comment]
Hello @Anzumana . Yes, this repo will soon be put on read-only.
All the work happens now in the mozilla-central repository.
You can read more about it here https://docs.firefox-dev.tools/getting-started/
