### ISSUE TITLE
"yarn start" fails with MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by 10ko** [firefox-devtools/debugger#8250]
Hello there, I am getting this error after a fresh `yarn install`:
```
✔ ~/code/debugger [master|✚ 1]
12:16 $ yarn start
yarn run v1.17.3
$ node bin/dev-server
Listening for WS on localhost:8116, all traffic is proxied to localhost:6080
Protocol messages can be logged by enabling `logging.firefoxProxy` `in /configs/local.json`
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'devtools-mc-assets'
Require stack:
- /Users/emanuele/code/debugger/node_modules/devtools-launchpad/src/development-server.js
- /Users/emanuele/code/debugger/node_modules/devtools-launchpad/index.js
- /Users/emanuele/code/debugger/bin/dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at Object.startDevServer (/Users/emanuele/code/debugger/node_modules/devtools-launchpad/src/development-server.js:187:26)
    at Object.<anonymous> (/Users/emanuele/code/debugger/bin/dev-server.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/emanuele/code/debugger/node_modules/devtools-launchpad/src/development-server.js',
    '/Users/emanuele/code/debugger/node_modules/devtools-launchpad/index.js',
    '/Users/emanuele/code/debugger/bin/dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My environment:
```
yarn: 1.17.3
node: v12.4.0
npm: 6.9.0
```

Does anybody have any pointer?
Thanks a lot.
E

**Comment by bomsy** [comment]
Hey 10Ko,

This is likely because this is no longer actively being maintained here and everything has been moved to the mozilla-central repo.

For details See https://firefox-source-docs.mozilla.org/devtools/getting-started/build.html#building-and-running-locally

Closing this for now.

**Comment by 10ko** [comment]
Hi @bomsy, thanks for letting me know!
